### ISSUE TITLE
Support to upcoming v11

### ISSUE THREAD

**Issue by cabello** [BlairCurrey/trpc-koa-adapter#31]
We have been using trpc-koa-adapter and trpc v11 release candidate in production for a while without any issues:

The following warning, could be mitigated with a simple change to package.json would you accept a PR?

> @trpc/server is listed by your project with version 11.0.0-rc.421 (pcff91), which doesn't satisfy what trpc-koa-adapter requests (^10.0.0-rc.4).

Thank you

**Comment by BlairCurrey** [comment]
Hi @cabello, thank you for chiming in. Widening the expected versions is more than welcome but I noticed there is actually a minor build error when using v11, as well as some trpc export changes which break the trpc-koa-adapter test mocks. Nothing that would affect using it, as you've noticed, but a few required changes nonetheless. Its something I intend on resolving but a PR is welcome if you still feel inclined.

**Comment by justinfagnani** [comment]
I hit this problem when I upgraded a library that now requires `@trpc/server` 11.

I took a crack at updating `@trpc/server` here, and I didn't see any build errors (though I've seen them around the Router and BuiltRouter types elsewhere), but I did hit failing tests, like:

```
  ● Unit › should return a function accepting 2 arguments

    TypeError: Cannot redefine property: nodeHTTPRequestHandler
        at Function.defineProperty (<anonymous>)

      15 |   beforeEach(async () => {
      16 |     spyNodeHTTPRequestHandler = jest
    > 17 |       .spyOn(nodeHTTPAdapter, 'nodeHTTPRequestHandler')
         |        ^
      18 |       .mockImplementationOnce(jest.fn());
      19 |   });
      20 |

      at ModuleMocker.spyOn (node_modules/jest-mock/build/index.js:776:16)
      at test/createKoaMiddleware.test.ts:17:8
      at test/createKoaMiddleware.test.ts:41:71
      at Object.<anonymous>.__awaiter (test/createKoaMiddleware.test.ts:37:12)
      at Object.<anonymous> (test/createKoaMiddleware.test.ts:15:25)
```

I don't know enough about Jest to know how to address that.

edit: oh, that's trying to spy on a module export. Module record objects are immutable, so I don't see how that's supposed to work.
